apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
      version: blue
  template:
    metadata:
      labels:
        app: cart-service
        version: blue
    spec:
      containers:
        - name: cart-service
          image: europe-west2-docker.pkg.dev/csc8113-453518/bookstore-repo/cart-service::{{IMAGE_TAG}}
          ports:
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
      version: green
  template:
    metadata:
      labels:
        app: cart-service
        version: green
    spec:
      containers:
        - name: cart-service
          image: europe-west2-docker.pkg.dev/csc8113-453518/bookstore-repo/cart-service::{{IMAGE_TAG}}
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
