apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-green
spec:
  replicas: 0 # Not running yet
  selector:
    matchLabels:
      app: catalog-service
      version: green
  template:
    metadata:
      labels:
        app: catalog-service
        version: green
    spec:
      containers:
        - name: catalog-service
          image: europe-west2-docker.pkg.dev/csc8113-453518/bookstore-repo/catalog-service:3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: "postgresql://postgres:mysecretpassword@bookstore-db:5432/bookstore"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi



