apiVersion: v1
kind: Service
metadata:
  name: catalog-green-service
spec:
  selector:
    app: catalog-service
    version: green
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer