# rbac-config.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deployment-updater
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-updater-binding
  namespace: default
subjects:
- kind: User
  name: "ggithub-actions@csc8113.iam.gserviceaccount.com"  # 替换为您的服务账号邮箱
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployment-updater
  apiGroup: rbac.authorization.k8s.io